cleanup and fixes

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -82,6 +82,22 @@ function generate_ts_from_dtos
 echo "Generating typescript dto definitions"
 generate_ts_from_dtos
 
+## We generate the ts signals interface for the C# signal methods before pushing
+function generate_ts_interfaces
+{
+    dotnet build Utilities/GenerateTypescriptInterfaces
+    dotnet Utilities/GenerateTypescriptInterfaces/bin/Debug/netcoreapp3.1/GenerateTypescriptInterfaces.dll
+    if [[ "$?" != 0 ]]; then 
+        printf "\e[31mThere was an error generating the SQE typescript SignalR interface.\n"
+        printf "Please fix these errors before continuing to commit your changes.\e[0m\n"
+        exit 1
+    fi 
+}
+
+## Generating typescript definitions
+echo "Generating typescript SignalR interface"
+generate_ts_interfaces
+
 ## Now add any updated files
 git add -A
 
